title: Carla A. Rudder # your name (or website title) here
logo: "/images/Head Shot u.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-driven professional with a strong background in mathematics, statistics, data analysis, and education. 
  My passion lies in utilizing data to find insights, drive innovation and create meaningful change.
  Technical Skills: SQL, Python, R, and Tableau to clean, organize, and visualize data for impactful insights. 
  <br><br>
  Certified Scrum Master
  <br><br>
  Applied Data Science & ML - MIT <br><br>
  
  BSc Applied Mathematics <br><br>       
  
  MSc Mathematics Ed (Financial Math) <br><br>  
  
  Ph.D. Mathematics Ed (Problem-Solving)    
 
  <br><br>
  <a href="https://www.linkedin.com/in/carudder/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
## google_analytics: UA-000000-0 # your Google Analytics tracking ID here
